
const notesData = [
    {
      id: 1,
      time: '2023-07-27T12:00:00',
      content: "У меня будет визит к стоматологу 3/5/2021, перенёс его с 5/5/2021",
      category: 'Task',
      dates: ['3/5/2021', '5/5/2021'],
      archived: false,
    },
    {
      id: 2,
      time: '2023-07-28T14:30:00',
      content: "Написать отчет о выполненной работе",
      category: 'Task',
      dates: [],
      archived: false,
    },
    {
      id: 3,
      time: '2023-07-29T09:15:00',
      content: "Идея: создать приложение для заметок",
      category: 'Idee',
      dates: [],
      archived: false,
    },
    {
      id: 4,
      time: '2023-07-30T18:00:00',
      content: "Приготовить ужин для гостей",
      category: 'Task',
      dates: [],
      archived: false,
    },
    {
      id: 5,
      time: '2023-07-31T10:00:00',
      content: "Купить продукты: молоко, яйца, овощи",
      category: 'Task',
      dates: [],
      archived: false,
    },
    {
      id: 6,
      time: '2023-08-01T16:45:00',
      content: "Захватывающая идея для нового проекта",
      category: 'Idee',
      dates: [],
      archived: false,
    },
    {
      id: 7,
      time: '2023-08-02T11:30:00',
      content: "Случайная мысль: посмотреть новый фильм",
      category: 'Случайная мысль',
      dates: [],
      archived: false,
    },
  ];
  
